services:
  - type: web
    name: income-expense-dialogflow
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: OCR_PROVIDER
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SPREADSHEET_ID
        sync: false
      - key: GOOGLE_SHEET_NAME
        sync: false
      - key: IAPP_API_KEY
        sync: false
      - key: APPMAN_API_KEY
        sync: false
      - key: SPACEOCR_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-southeast-1
    healthCheckPath: /health
